# Gradle

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties

mod_id=quad
mod_name=Quad
mod_version=1.2.17
mod_license=MIT
mod_group=dev.lieonlion.quad
mod_author=LieOnLion
mod_description=Expanding the power of Data-Driven possibilities.
# Links
mod_link_homepage=https://lieonlion.dev/
mod_link_sources=https://github.com/lieonlion/quad
mod_link_issues=https://github.com/lieonlion/quad/issues

# Common

minecraft_version=26.2
minecraft_fabric_version_range=>=26.1
minecraft_neo_version_range=[26.1,)
java_version=25

# Fabric

fabric_version=0.152.2+26.2
fabric_loader_version=0.18.5
loom_version=1.17-SNAPSHOT

# NeoForge

neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)
neoforge_moddev_version=2.0.141
neo_form_version=26.2-1

# Dependencies

# Sodium Properties
sodium_version=0.9.0
sodium_minecraft_version=26.2

# ModMenu Properties
modmenu_version=v20.0.0-beta.3
